# Generated by Django 5.2.3 on 2026-02-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membershipPlan',
            field=models.CharField(default='Basic', max_length=255),
            preserve_default=False,
        ),
    ]
